# Generated by Django 6.0.2 on 2026-02-23 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_idempotency_key_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='uniq_provider_idempotency',
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('provider', 'user', 'idempotency_key'), name='uniq_provider_user_idempotency'),
        ),
    ]
